### ISSUE TITLE
--with-edit documentation is inconsistent

### ISSUE THREAD

**Issue by TobyGoodwin** [TobyGoodwin/rc-pure-git#4]
Christian Neukirchen points out:

>I just noticed that the output of configure --help
>  --with-edit=(bsd,edit,gnu,vrl)  Command line editing library
>
>AFAICS only bsd and gnu work?

In truth, I never got round to writing the shims for edit / vrl. In fact, I haven't looked at either of these libraries in well over a decade, and I suspect nobody else has either, in which case I'd be tempted to drop support for them.

I do feel it would be nice to have an alternative to GNU readline. Although Moore's law largely wipes out the efficiency concerns, the kitchen-sink approach is still an ugly design. Possibly I might be tempted to take on one of the alternatives for ongoing maintenance, although realistically my time is very scarce, and I certainly couldn't do both.

Anyway, the first action here is to investigate the health and liveness of the edit and vrl libraries.

**Comment by chneukirchen** [comment]
I think libedit is a good BSD-licensed alternative already.

Linenoise (https://github.com/antirez/linenoise) could be interesting because it's rather small and has no deps on external libraries (vt100 hardcoded I guess), making it a good choice for static linking.  Has multi-line editing and a history feature, as well as generic completion (no file name completion built-in afaics).  Pulls in stdio however (just a few snprintf and sscanf, could be rewritten I think).

**Comment by TobyGoodwin** [comment]
Well, it looks like editline is still alive: https://github.com/troglobit/editline

I've tried to contact Gert-Jan Vons about vrl, although his website doesn't seem to have been touched for about 7 years.

**Comment by TobyGoodwin** [comment]
Gert-Jan replied to say that vrl-1.3.3 is the latest version that he has released, and there is also a derivative https://github.com/system-construction/vrl

**Comment by TobyGoodwin** [comment]
the shims now exist in rc-1.7.3 - minimal testing though
